### ISSUE TITLE
xml plugin needs to verify jrunscript exists

### ISSUE THREAD

**Issue by aw-altiscale** [aw-altiscale/pre-yetus#30]
openjdk doesn't install with jrunscript normally.

**Comment by sekikn** [comment]
I'll add the verification. Is the environment Ubuntu? In my understanding, openjdk-devel package on RHEL-like systems includes jrunscript as well as javac et al.

**Comment by aw-altiscale** [comment]
Yes, I hit this on Ubuntu  (of course. *sigh*) while playing around with the docker bugs.

**Comment by sekikn** [comment]
That plugin has a verification already. I forgot.

```
 28 function xml_postapply
 29 {

 41   js="${JAVA_HOME}/bin/jrunscript"
 42   if [[ ! -x ${js} ]]; then
 43     yetus_error "${js} does not exist"
 44     return 0
 45   fi
```

The problem is, is returning 0 proper? Shellcheck plugin behaves in the same way.

```
 56 function shellcheck_preapply
 57 {
 58   local i
 59   local msg
 60 
 61   verify_needed_test shellcheck
 62   if [[ $? == 0 ]]; then
 63     return 0
 64   fi
 65 
 66   big_console_header "shellcheck plugin: prepatch"
 67 
 68   if [[ ! -x "${SHELLCHECK}" ]]; then
 69     yetus_error "shellcheck is not available."
 70     return 0
 71   fi
```

But findbugs returns 1.

```
178 function findbugs_preapply
179 {

196   findbugs_is_installed
197   if [[ $? != 0 ]]; then
198     return 1
199   fi
```

Should we standardize them to 1 for assuring quality?

**Comment by aw-altiscale** [comment]
OK, this is weird then.  Let's close this and I'll retry now that I've got docker working again.   If it fails again, I'll re-open on JIRA.
