### ISSUE TITLE
whitespace check is extremely slow

### ISSUE THREAD

**Issue by aw-altiscale** [aw-altiscale/pre-yetus#31]
this could be optimized by at least checking for failures prior to running the larger tests.

**Comment by sekikn** [comment]
We have some options:

* Give whitespace plugin special treatment. Call it before check_patch_javac in postapply directly and exclude it in the later loop. (dirty)
* Split postapply hooks into two, such as postapply_(before|after)_routine. (yes, we need some simpler name. Also other hooks which have routine functions?)
* Some more generic feature to specify the priority of a plugin. (no concrete idea yet)

**Comment by aw-altiscale** [comment]
I was thinking about this while driving around doing errands today.  What if we modify compute_gitdiff to generate two flies, one with the raw numbers like today and one with the numbers and the contents of the added lines.  You could then run whitespace (and maybe other checks in the future?) against that file rather than going through all of the lines of all of the content.  It could cut back the amount of work significantly.

**Comment by aw-altiscale** [comment]
This method works great. Closing.

**Comment by sekikn** [comment]
Yeah, it improves 26s to <1s in my environment as well. Great.
It also found tab problems in HADOOP-12113-HADOOP-12111.patch. Probably substantial bug was fixed.

```
[sekikn@mobile pre-yetus]$ cat /private/tmp/test-patch-hadoop/17683/whitespace-tabs.txt
./dev-support/personality/flink.sh:84:	if [[ "${FLINK_POST_LIB_FILES}" -gt "${FLINK_PRE_LIB_FILES}" ]]; then
./dev-support/personality/flink.sh:91:	else
./dev-support/personality/flink.sh:94:	fi
./dev-support/test-patch-docker/Dockerfile-startstub:74:	    -O /tmp/jiracli.zip && \
```

**Comment by aw-altiscale** [comment]
Yeah. I'm going to post a new version later today. Lots of bug fixed since that was posted.
