### ISSUE TITLE
Pig "tar" target is not executed on the pre-patch javac process

### ISSUE THREAD

**Issue by sekikn** [aw-altiscale/pre-yetus#32]
Running Pig personality on master branch, I found a strange behaviour.

The pre-patch javac process succeeded, 

```
[sekikn@localhost pre-yetus]$ precommit/main/test-patch.sh --basedir=../pig --project=pig PIG-4581      

(snip)

============================================================================
============================================================================
                     Pre-patch trunk Java compilation
============================================================================
============================================================================


ant -DPigPatchProcess= -Djavac.args=-Xlint -Dcompile.c++=yes clean tar > /tmp/test-patch-pig/25671/branch-javac-root.txt 2>&1
Elapsed:   0m 52s

(snip)
```

but "tar" target isn't executed. Instead, "jar" target seems to be executed.

```
[sekikn@localhost pre-yetus]$ tail -25 /tmp/test-patch-pig/25671/branch-javac-root.txt

jar:
     [echo] svnString exported
      [jar] Building jar: /home/sekikn/pig/build/pig-0.16.0-SNAPSHOT.jar
     [echo] svnString exported
      [jar] Building jar: /home/sekikn/pig/build/pig-0.16.0-SNAPSHOT-withouthadoop.jar
      [jar] META-INF/ASL2.0 already added, skipping
      [jar] META-INF/LICENSE already added, skipping
      [jar] META-INF/NOTICE already added, skipping

copyCommonDependencies:
    [mkdir] Created dir: /home/sekikn/pig/lib
     [copy] Copying 33 files to /home/sekikn/pig/lib

copyh1Dependencies:
    [mkdir] Created dir: /home/sekikn/pig/lib/h1
     [copy] Copying 8 files to /home/sekikn/pig/lib/h1
     [copy] Copying 1 file to /home/sekikn/pig
    [mkdir] Created dir: /home/sekikn/pig/legacy
     [move] Moving 1 file to /home/sekikn/pig/legacy

copyh2Dependencies:

BUILD SUCCESSFUL
Total time: 50 seconds
```

**Comment by sekikn** [comment]
And, is the "tar" target too much for the javac process? "jar" and "piggybank" targets may be enough.

**Comment by aw-altiscale** [comment]
Like the other personalities, pig's is using what that project had in their own test-patch code.  So there are bound to be optimizations that can be made.  I'm hoping to give the individual projects their own personalities that they can then own/modify as needed.

**Comment by sekikn** [comment]
Make sense. But the situation has changed a little. Currently, pig personality always fails at precheck_javac and check_patch_javac by the following error:

```
forrest.check:

BUILD FAILED
/Users/sekikn/pig/build.xml:648: 'forrest.home' is not defined.       Please pass -Dforrest.home=<base of Apache Forrest installation> to Ant on the command-line.
```

This is because "tar" target depends on "docs" via "package". I'd like to ship Yetus in the state that runs successfully in a normal case, because it will give a good impression and increase the possibility that the community is willing to accept Yetus.

**Comment by aw-altiscale** [comment]
I'm hoping we can push the personality modules to their respective projects so that they can maintain them.  This way if they have weird requirements like this, they deal with them. haha.

But yeah, if we should change tar to something else, let's do it.  

While I'm thinking about it, we should probably start moving development over to JIRA now that we have a branch over at Apache.

**Comment by sekikn** [comment]
OK, once HADOOP-12113 is committed, let's move remaining issues into JIRA.

**Comment by aw-altiscale** [comment]
I'll let you open the JIRA for this. :+1:

**Comment by sekikn** [comment]
Moved to JIRA. Thanks!
