### ISSUE TITLE
Git <1.7.3 does not support -e option for git clean command

### ISSUE THREAD

**Issue by sekikn** [aw-altiscale/pre-yetus#33]
I tried to test #28, but my git version was 1.7.1 (default on CentOS 6.6) and it does not support -e option for clean subcommand, so it failed. Should we restrict or warn if the git version is not enough?

**Comment by aw-altiscale** [comment]
I'll let you open the JIRA for this. :+1:

**Comment by sekikn** [comment]
Thanks! Moved to JIRA.
