### ISSUE TITLE
Docker support is partially broken

### ISSUE THREAD

**Issue by aw-altiscale** [aw-altiscale/pre-yetus#35]
Playing around, it looks like docker support is pretty broken in a number of surprising ways.  I'll use this to summarize the problems:

* separate test-patch location outside of basedir
* patch file can't be found if not JIRA or URL
* personality file uses defaults, not provided
* user-plugins aren't handled properly

**Comment by aw-altiscale** [comment]
OK, I'm opting to effectively throw out the current design of re-exec and docker mode in order to integrate them together.  This solves a good chunk of the given problems.

**Comment by sekikn** [comment]
You mean running test-patch in docker container if re-exec needed? Sounds reasonable.

**Comment by aw-altiscale** [comment]
Yeah, I'm basically consolidating reexec and docker into one.  Today, they are handled separately and it causes all sorts of weird problems.  Now that we've expanded the amount of things that people can plug, it's gotten unwieldly.  So I'm changing the matrix to look like this:

|dockermode|test-patch patch|Outcome|
|---- |---- | --- |
| no | yes | patch -> copy -> re-exec local |
| yes | no | copy -> re-exec in docker |
| yes | yes | patch -> copy -> re-exec in docker |

**Comment by aw-altiscale** [comment]
Also, this all happens in basically one chunk of code rather than 3 or so.
