### ISSUE TITLE
Download GitHub pull request instead of JIRA attached patch

### ISSUE THREAD

**Issue by sekikn** [aw-altiscale/pre-yetus#8]
I tried the Tajo personality, but it failed. This is because Tajo's workflow is based on pull-request, not attached patches.

```
[sekikn@localhost pre-yetus]$ precommit/main/test-patch.sh --basedir=../tajo --personality=precommit/main/personality/tajo.sh TAJO-1633


============================================================================
============================================================================
                        Bootstrapping test harness
============================================================================
============================================================================


/tmp/test-patch-yetus/10160 has been created
Running in developer mode
 patch is being downloaded at Thu Jun 11 03:44:25 UTC 2015 from
http://issues.apache.org
ERROR: http://issues.apache.org is not a patch file.


============================================================================
============================================================================
                              Finished build.
============================================================================
============================================================================
```

**Comment by aw-altiscale** [comment]
I've been thinking about this and related PRs of yours over the past few days and I think our general approach here and with --bugsystems is wrong.

Ideally, I'd like to be able to pull and write to multiple bug systems at once.  For example, if Jenkins is testing a flink patch, it should be able to pull from the github pr and update both the related JIRA issue and the github PR comment.

So I think the proper way to fix this might be to have a prefix on the issue.  i.e.:

{code}
test-patch.sh github:flink/99 jira:FLINK-99
{code}

or whatever.  test-patch could cycle through both and looking for either the first match or try to figure out what the latest version is or whatever.


That aside, we'll actually need the full URL later on when the ability to write to a github PR gets implemented.

**Comment by aw-altiscale** [comment]
More thoughts, combining with #9 .

if --bugsystem is JIRA then we do a few things:

* if jira status = closed, unresolved, exit.
* if jira status = patch available, then we look for a patch in the jira. 
* if jira status = (anything else), we look for a github pr.

a) what if you are using a jira with direct github integration?  We have that at altiscale.  need to see what that looks like.
b) do github pr's have a state that can be queried? there's lots of things missing in the current github support and this is probably one of them.

Regardless, we should move the download logic for github and jira into their respective plugins.  We need to design an API/vars/whatever for communication here.  I think.

**Comment by aw-altiscale** [comment]
I've opened this as HADOOP-12129 .
